// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PortingAssistantVSExtensionClient.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPortingAssistantVSExtensionClientPackageString = "89507157-95b2-4fa0-beac-c5d42bdaa734";
        public static Guid guidPortingAssistantVSExtensionClientPackage = new Guid(guidPortingAssistantVSExtensionClientPackageString);

        public const string guidAnalyzeMenuGroupString = "cd68f8e6-2842-4f7e-af7b-5a019631ceb5";
        public static Guid guidAnalyzeMenuGroup = new Guid(guidAnalyzeMenuGroupString);

        public const string guidPortingAssistantVSExtensionClientPackageCmdSetString = "72f43848-037a-4907-98e2-e7e964271f44";
        public static Guid guidPortingAssistantVSExtensionClientPackageCmdSet = new Guid(guidPortingAssistantVSExtensionClientPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int IDM_DIAG_TOPLEVELMENU = 0x0001;
        public const int TopLevelMenu = 0x1010;
        public const int PADiagGroup = 0x1020;
        public const int PAProjMenuGroup = 0x1030;
        public const int PAProjectGroup = 0x1040;
        public const int PATopMenuGroup = 0x1050;
        public const int PASolutionGroup = 0x1060;
        public const int SolutionAssessmentCommandId = 0x0100;
        public const int cmdidSolutionPortingCommand = 0x0101;
        public const int cmdidProjectPortingCommand = 0x0102;
        public const int cmdidAutoAssessmentCommand = 0x0103;
        public const int cmdidDisplaySettings = 0x0104;
    }
}