// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PortingAssistantVSExtensionClient.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPortingAssistantVSExtensionClientPackageString = "89507157-95b2-4fa0-beac-c5d42bdaa734";
        public static Guid guidPortingAssistantVSExtensionClientPackage = new Guid(guidPortingAssistantVSExtensionClientPackageString);

        public const string guidPortingAssistantVSExtensionClientPackageCmdSetString = "72f43848-037a-4907-98e2-e7e964271f44";
        public static Guid guidPortingAssistantVSExtensionClientPackageCmdSet = new Guid(guidPortingAssistantVSExtensionClientPackageCmdSetString);

        public const string guidImagesString = "6776e3d2-6672-45f7-8cc0-5c3a9010ed45";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PAMenuGroup = 0x1020;
        public const int PAProjectGroup = 0x1030;
        public const int SolutionAssessmentCommandId = 0x0100;
        public const int cmdidSolutionPortingCommand = 0x1021;
        public const int cmdidProjectPortingCommand = 0x1022;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}